### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by netnazgul** [nathanj/ogsdroid#1]
Using the latest v0.7 e465052ba40f4694010d3204f9f5796cca14e225
Can't login, just keeps saying "your password is incorrect" even though that same login/password works on OGS website

**Comment by nathanj** [comment]
Does your username or password have any special characters in it? I wonder if something is not getting escaped properly. If so, try changing your password to something simpler temporarily to see if it works.

If that doesn't work, can you try using the API directly by running the below command and post the error here? Replace USERNAME and PASSWORD with yours.

```
curl --include \
     --request POST \
     --header "Content-Type: application/x-www-form-urlencoded" \
     --data-binary "client_id=com.ogsdroid&client_secret=sai&grant_type=password&username=USERNAME&password=PASSWORD" \
'https://online-go.com/oauth2/token/'
```

**Comment by netnazgul** [comment]
{"error_description": "Invalid credentials given.", "error": "invalid_grant"}

looks like it's indeed something with authenticating through API, but on their side.

upd: yeah, and also "HTTP/1.1 401 Unauthorized" at the beginning.

**Comment by netnazgul** [comment]
Used "update password" and entered the same password I had before. This solved the issue.
