### ISSUE TITLE
Release 0.9.1

### ISSUE THREAD

**Issue by BHydden** [nathanj/ogsdroid#10]
There is no .apk link for v0.9.1

**Comment by ildar** [comment]
must come to f-droid soon

**Comment by ildar** [comment]
Actually it's there already:
https://f-droid.org/repository/browse/?fdid=com.ogsdroid

**Comment by BHydden** [comment]
Thanks ildar I didn't know about f-droid :) I'll check there in future

**Comment by nathanj** [comment]
Yes I was testing to see how the f-droid update process works. It is a bit slow as it took 3 days to update after I pushed it.
