### ISSUE TITLE
Games don't show up

### ISSUE THREAD

**Issue by Seferi** [nathanj/ogsdroid#8]
Hi mate, just downloaded your app from F-droid. Somehow my games from ogs don't showup under my games tab. Oneplus device, LineageOS, Android 7.1.2

**Comment by nathanj** [comment]
Can you collect the logcat and send it to me? There have been some other reports of this happening, but I cannot reproduce on my devices.

**Comment by Seferi** [comment]
thanks for the quick reply mate, here is the logcat:
[2017-05-26-16-25-54.txt](https://github.com/nathanj/ogsdroid/files/1032139/2017-05-26-16-25-54.txt)

**Comment by nathanj** [comment]
That log is very strange. It doesn't have all of the traces. For instance, in the source code is this fragment:
```
        println("NJJJ logger = ${logger}")
        println("NJJJ logger.level = ${logger.level}")
        println("NJJJ logger.name = ${logger.name}")
```
However your log file only has the last line:
```
05-26 16:24:34.630 I/System.out(29501): NJJJ logger.name = com.ogs.OgsSocket
```
I don't know why only some of the traces would show up. Can you try collecting again, or maybe through a different method to see if you get more logs?

I haven't installed the fdroid version of the app yet, so it could be something that fdroid does when it builds that gets rid of the logging. I will try it tonight.

**Comment by Seferi** [comment]
I recorded another log, this time without any filter:
[log.txt](https://github.com/nathanj/ogsdroid/files/1032950/log.txt)

**Comment by nathanj** [comment]
Thanks! I see the issue. It should be an easy fix. I am hoping to release a new version tonight if all goes well.

**Comment by Seferi** [comment]
Thanks mate, looking forward to the new version.
